version: '3'
services:
  openresty1:
    image: openresty/openresty:alpine-fat
    container_name: openresty1
    ports:
      - "60002:60002"
    volumes:
      - ./logs:/usr/local/openresty/nginx/logs
      - ./html:/usr/local/openresty/nginx/html
      - ./lua:/usr/local/openresty/nginx/lua
      - ./conf:/usr/local/openresty/nginx/conf
    restart: always
networks:
  openresty1:
    driver: bridge

